### ISSUE TITLE
nová otázka - kategorie se špatně přenáší

### ISSUE THREAD

**Issue by PalkaPatrik** [marcovindy/egghead#25]
mezi otázkami se přenáší kategorie, ale formulář to nebere jako validně vybrané

<img width="685" alt="Screenshot 2023-05-06 at 7 59 28" src="https://user-images.githubusercontent.com/27286804/236603499-514fa5c7-0180-4b38-925a-9b851361cd6f.png">

**Comment by marcovindy** [comment]
Fixed
