### ISSUE TITLE
Hra - zaokrouhlení skóre

### ISSUE THREAD

**Issue by PalkaPatrik** [marcovindy/egghead#27]
Chtělo by to zaokrouhlit skóre třeba na 2 desetinná.

<img width="664" alt="Screenshot 2023-05-07 at 10 43 12" src="https://user-images.githubusercontent.com/27286804/236668077-820714ba-767f-4805-af1f-0cda60225581.png">
<img width="431" alt="Screenshot 2023-05-07 at 10 58 36" src="https://user-images.githubusercontent.com/27286804/236668078-b5c6fbe9-2830-485a-a3c7-0a029c0d3621.png">

**Comment by marcovindy** [comment]
Fixed
